name: Deploy Chat API to Azure Web App

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (Optional) Run tests here if you have any
      # - name: Run tests
      #   run: pytest

      - name: Archive application for deployment
        run: zip -r app.zip . -x 'venv/*' '.git/*' '__pycache__/*'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip

      # (Optional) Restart the web app after deployment
      # - name: Restart Azure Web App
      #   run: az webapp restart --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group <your-resource-group>
      #   env:
      #     AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }} 